services:
  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=mystrongpassword
    command: [ "redis-server", "--requirepass", "mystrongpassword" ]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
